name: Desplegar Vue App a action1
run-name: ${{ github.actor }} està pujant la seva App Vue a action2 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositori
        uses: actions/checkout@v4

      - name: Instalar dependencias
        working-directory: ./calculadora
        run: npm i

      - name: Construir la aplicación
        working-directory: ./calculadora
        run: npm run build

      - name: Verificar contenido build
        working-directory: ./calculadora
        run: ls -la dist

      - name: Crear clave SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem


      - name: Enviar archivos al servidor
        working-directory: ./calculadora
        run: |
          scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -i ~/prod_key.pem ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/web/a22kevburcac.daw.inspedralbes.cat/public_html/action2/
          rm ~/prod_key.pem


      - name: Fi del procés
        run: echo "🎉 Desplegament completat a action1!"